### PR TITLE
Remove xml fields

### PR DESCRIPTION
**Pull request by andygnewman**
cc: @i-like-robots

Migrates from XML to HTML in subheading transform.

### CODE REVIEW

**Comment by i-like-robots** [comment]
I guess we need to wait for https://github.com/Financial-Times/next-es-interface/pull/524 ?

**Comment by andygnewman** [comment]
Probably wise too, however I don't think it would have much negative impact even if it went early.

Was always meaning to review this subheading stuff, not sure whether we still need it. 

I guess the `n-teaser / n-card` review should review the needs of the content decorator.

**Comment by i-like-robots** [comment]
I don't think it should be necessary... again this is something that should be in ES

**Comment by andygnewman** [comment]
Closing as subheading transform (the only thing that was using the XML fields) has already been deprecated.

**Pull request closed without merging**
